import { describe, it, expect } from 'vitest'
import {
  Disciplina,
  EstadoDeportista,
  Genero,
  ActividadComplementaria,
  NivelEstudio,
  SituacionLaboral,
  MedioTransporte,
  CondicionVivienda,
  DificultadAlimentacion,
  TipoApoyo,
  Servicio,
} from '@/lib/generated/prisma/client'

// Type-level enum tests — no database connection required.
// These assertions confirm that every enum constant generated by Prisma
// matches the expected string value defined in prisma/schema.prisma.

describe('Deportista enums', () => {
  describe('Disciplina', () => {
    it('has all 21 correct values', () => {
      expect(Disciplina.FUTBOL).toBe('FUTBOL')
      expect(Disciplina.FUTSAL).toBe('FUTSAL')
      expect(Disciplina.BASQUET).toBe('BASQUET')
      expect(Disciplina.VOLEY).toBe('VOLEY')
      expect(Disciplina.HANDBALL).toBe('HANDBALL')
      expect(Disciplina.NATACION).toBe('NATACION')
      expect(Disciplina.ATLETISMO).toBe('ATLETISMO')
      expect(Disciplina.HOCKEY).toBe('HOCKEY')
      expect(Disciplina.RUGBY).toBe('RUGBY')
      expect(Disciplina.TENIS).toBe('TENIS')
      expect(Disciplina.GIMNASIA).toBe('GIMNASIA')
      expect(Disciplina.GIMNASIA_ARTISTICA).toBe('GIMNASIA_ARTISTICA')
      expect(Disciplina.PATIN).toBe('PATIN')
      expect(Disciplina.ARTES_MARCIALES).toBe('ARTES_MARCIALES')
      expect(Disciplina.COMBATE).toBe('COMBATE')
      expect(Disciplina.INICIACION_DEPORTIVA).toBe('INICIACION_DEPORTIVA')
      expect(Disciplina.POWER_CHAIR).toBe('POWER_CHAIR')
      expect(Disciplina.TIADE).toBe('TIADE')
      expect(Disciplina.AJEDREZ).toBe('AJEDREZ')
      expect(Disciplina.BOXEO).toBe('BOXEO')
      expect(Disciplina.OTRO).toBe('OTRO')
    })
  })

  // El enum Categoria se eliminó: la categoría del deportista es ahora una
  // relación FK al catálogo `categorias` (ver refactor categoria-enum-to-fk).

  describe('EstadoDeportista', () => {
    it('has all 4 correct values', () => {
      expect(EstadoDeportista.ACTIVO).toBe('ACTIVO')
      expect(EstadoDeportista.INACTIVO).toBe('INACTIVO')
      expect(EstadoDeportista.LESIONADO).toBe('LESIONADO')
      expect(EstadoDeportista.SUSPENDIDO).toBe('SUSPENDIDO')
    })
  })

  describe('Genero', () => {
    it('has all 4 correct values', () => {
      expect(Genero.MASCULINO).toBe('MASCULINO')
      expect(Genero.FEMENINO).toBe('FEMENINO')
      expect(Genero.NO_BINARIO).toBe('NO_BINARIO')
      expect(Genero.PREFIERO_NO_DECIR).toBe('PREFIERO_NO_DECIR')
    })
  })

  describe('ActividadComplementaria', () => {
    it('has all 4 correct values', () => {
      expect(ActividadComplementaria.GIMNASIO).toBe('GIMNASIO')
      expect(ActividadComplementaria.TECNICA_INDIVIDUAL).toBe('TECNICA_INDIVIDUAL')
      expect(ActividadComplementaria.AMBAS).toBe('AMBAS')
      expect(ActividadComplementaria.NINGUNA).toBe('NINGUNA')
    })
  })

  describe('NivelEstudio', () => {
    it('has all 9 correct values', () => {
      expect(NivelEstudio.PRIMARIO_INCOMPLETO).toBe('PRIMARIO_INCOMPLETO')
      expect(NivelEstudio.PRIMARIO_EN_CURSO).toBe('PRIMARIO_EN_CURSO')
      expect(NivelEstudio.PRIMARIO_COMPLETO).toBe('PRIMARIO_COMPLETO')
      expect(NivelEstudio.SECUNDARIO_INCOMPLETO).toBe('SECUNDARIO_INCOMPLETO')
      expect(NivelEstudio.SECUNDARIO_EN_CURSO).toBe('SECUNDARIO_EN_CURSO')
      expect(NivelEstudio.SECUNDARIO_COMPLETO).toBe('SECUNDARIO_COMPLETO')
      expect(NivelEstudio.TERCIARIO_INCOMPLETO).toBe('TERCIARIO_INCOMPLETO')
      expect(NivelEstudio.TERCIARIO_EN_CURSO).toBe('TERCIARIO_EN_CURSO')
      expect(NivelEstudio.TERCIARIO_COMPLETO).toBe('TERCIARIO_COMPLETO')
    })
  })

  describe('SituacionLaboral', () => {
    it('has all 3 correct values', () => {
      expect(SituacionLaboral.ALGUIEN_TRABAJA).toBe('ALGUIEN_TRABAJA')
      expect(SituacionLaboral.NADIE_TRABAJA).toBe('NADIE_TRABAJA')
      expect(SituacionLaboral.SIN_DATO).toBe('SIN_DATO')
    })
  })

  describe('MedioTransporte', () => {
    it('has all 4 correct values', () => {
      expect(MedioTransporte.TRANSPORTE_PUBLICO).toBe('TRANSPORTE_PUBLICO')
      expect(MedioTransporte.TRANSPORTE_FAMILIAR).toBe('TRANSPORTE_FAMILIAR')
      expect(MedioTransporte.TRANSPORTE_DEL_CLUB).toBe('TRANSPORTE_DEL_CLUB')
      expect(MedioTransporte.OTRO).toBe('OTRO')
    })
  })

  describe('CondicionVivienda', () => {
    it('has all 4 correct values', () => {
      expect(CondicionVivienda.PROPIA).toBe('PROPIA')
      expect(CondicionVivienda.CEDIDA).toBe('CEDIDA')
      expect(CondicionVivienda.ALQUILADA).toBe('ALQUILADA')
      expect(CondicionVivienda.OTRO).toBe('OTRO')
    })
  })

  describe('DificultadAlimentacion', () => {
    it('has all 3 correct values', () => {
      expect(DificultadAlimentacion.NUNCA).toBe('NUNCA')
      expect(DificultadAlimentacion.A_VECES).toBe('A_VECES')
      expect(DificultadAlimentacion.FRECUENTEMENTE).toBe('FRECUENTEMENTE')
    })
  })

  describe('TipoApoyo', () => {
    it('has all 7 correct values', () => {
      expect(TipoApoyo.ECONOMICO).toBe('ECONOMICO')
      expect(TipoApoyo.ALIMENTACION).toBe('ALIMENTACION')
      expect(TipoApoyo.TRANSPORTE).toBe('TRANSPORTE')
      expect(TipoApoyo.EDUCATIVO).toBe('EDUCATIVO')
      expect(TipoApoyo.PSICOLOGICO).toBe('PSICOLOGICO')
      expect(TipoApoyo.NINGUNO).toBe('NINGUNO')
      expect(TipoApoyo.OTRO).toBe('OTRO')
    })
  })

  describe('Servicio', () => {
    it('has all 9 correct values', () => {
      expect(Servicio.LUZ).toBe('LUZ')
      expect(Servicio.GAS).toBe('GAS')
      expect(Servicio.AGUA_CORRIENTE).toBe('AGUA_CORRIENTE')
      expect(Servicio.TELEFONO).toBe('TELEFONO')
      expect(Servicio.CABLE).toBe('CABLE')
      expect(Servicio.INTERNET).toBe('INTERNET')
      expect(Servicio.SEGURIDAD).toBe('SEGURIDAD')
      expect(Servicio.ALARMA).toBe('ALARMA')
      expect(Servicio.NINGUNA).toBe('NINGUNA')
    })
  })
})
